@baseUri = http://localhost:5214/

### Driver Write Location
POST {{baseUri}}/gps
Accept: application/json
Content-Type: application/json

{
  "driverName": "Allan Test",
  "latitude": 43.8530286,
  "longitude": -78.9401376,
  "heading": 180,
  "speed": 65,
  "timestamp": "2025-11-08T12:00:00Z"
}

### Driver Read Location
GET {{baseUri}}/drivers
Accept: application/json
Content-Type: application/json

### Read Company Drivers
GET {{baseUri}}/company/gonedotnet
Accept: application/json
Content-Type: application/json

### Driver Read Location
GET {{baseUri}}/drivers/Allan%20Test/coordinates
Accept: application/json
Content-Type: application/json